[[constraint]]
  name = "github.com/alecthomas/chroma"
  source =  "github.com/dgageot/chroma"
  branch = "support-copy-docker"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/jaschaephraim/lrserver"
  version = "3.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/radovskyb/watcher"
  version = "1.0.2"

[[constraint]]
  name = "github.com/yudai/gotty"
  version = "2.0.0-alpha.3"

[prune]
  go-tests = true
  unused-packages = true
